<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('settings')->delete();

        \DB::table('settings')->insert(array (
            0 =>
            array (
                'id' => 1,
                'key' => 'general-setting',
                'type' => 'general-setting',
                'value' => '{"site_name":"Handyman Service","site_description":"Launch your own mobile-based online On-Demand Home Services with Handyman Service mobile app. The customizable templates of this amazing app can quickly let developers to set up a service booking system to accept bookings from clients from anywhere in only a few minutes. With ready to use Sign in page, Sign up pages, Payment methods page, Booking lists, Service Type demo, Handyman detail page, Coupon page, and more, this Handyman Service app allows business to have a complete and running booking service system app in no time.The provider in this Handyman Service app can assign the booking to Handyman and accelerate the service. This Handyman Service system app comes with a Laravel PHP admin panel to have a meaningful insights from the admin dashboard and statistics. Assign multi-roles and permissions like Admin, Service Provider, Handyman, and customers using this app. Additionally, this Handyman Service app supports Multiple Language/ RTL support. This customizable, ready-to-use app comes with light as well as dark theme support and push notification to engage with clients in a more interactive way.","inquriy_email":"hello@iqonic.design","helpline_number":"+15265897485","website":"https://apps.iqonic.design/handyman/","country_id":"231","state_id":"3956","city_id":"47855","zipcode":"12201","address":"45 HUDSON AVE UNIT 1296 ALBANY NY 12201-6256 USA"}',
            ),
            1 =>
            array (
                'id' => 2,
                'key' => 'theme-setup',
                'type' => 'theme-setup',
                'value' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'key' => 'site-setup',
                'type' => 'site-setup',
                'value' =>'{"date_format":"F j, Y","time_format":"g:i A","time_zone":"Asia/Kolkata","language_option":["nl","fr","it","pt","es","en","ar"],"default_currency":"231","currency_position":"left","google_map_keys":"AIzaSyCtTed7y_ePqg1QoDMHOyu01FtP_Ot-mDU","latitude":null,"longitude":null,"distance_type":"km","radious":"50","digitafter_decimal_point":"2","android_app_links":1,"playstore_url":"https://play.google.com/store/apps/details?id=com.iqonic.servicebooking","provider_playstore_url":"https://play.google.com/store/apps/details?id=com.iqonic.provider","ios_app_links":1,"appstore_url":"https://apps.apple.com/us/app/handyman-service-user/id1591427211","provider_appstore_url":"https://apps.apple.com/in/app/handyman-provider-app/id1596025324","site_copyright":"© 2024 All Rights Reserved by IQONIC Design"}',
            ),
            3 =>
            array (
                'id' => 4,
                'key' => 'service-configurations',
                'type' => 'service-configurations',
                'value' =>'{"advance_payment":1,"slot_service":1,"digital_services":1,"service_packages":1,"service_addons":1,"post_services":1}',
            ),
            4 =>
            array (
                'id' => 5,
                'key' => 'OTHER_SETTING',
                'type' => 'OTHER_SETTING',
                'value' => '{"social_login":1,"google_login":1,"apple_login":1,"otp_login":1,"online_payment":1,"blog":1,"maintenance_mode":0,"wallet":1,"enable_chat_gpt":1,"test_without_key":1,"chat_gpt_key":null,"force_update_user_app":0,"user_app_minimum_version":null,"user_app_latest_version":null,"force_update_provider_app":0,"provider_app_minimum_version":null,"provider_app_latest_version":null,"force_update_admin_app":0,"admin_app_minimum_version":null,"admin_app_latest_version":null,"firebase_notification":1,"project_id":"bookingsystem-3be5c","auto_assign_provider":0, "dashboard_type":"dashboard"}',
            ),
            5 =>
            array (
                'id' => 6,
                'key' => 'social-media',
                'type' => 'social-media',
                'value' => '{"facebook_url":"https://www.facebook.com/iqonicdesign/","linkedin_url":"https://www.linkedin.com/company/iqonicthemes/","instagram_url":"https://www.instagram.com/iqonicdesign/?igshid=YmMyMTA2M2Y%3D","youtube_url":"https://www.youtube.com/iqonicdesign","twitter_url":"https://twitter.com/iqonicdesign"}',
            ),


            6 =>
            array (
                'id' => 7,
                'key' => 'terms_condition',
                'type' => 'terms_condition',
            'value' => '<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">By accessing products on this site and placing an order from our website, you confirm that you are in agreement with and bound by the terms and conditions presented and outlined here. These terms apply to the entire website and any email or other type of communication between you and Iqonic Design. The Iqonic Design team is not liable for any direct, indirect, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use the materials on this site.<br /><br style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;" />Iqonic Design will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Products</span></h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">All products and services offered on this site are produced by Iqonic Design. You can access your download from your respective dashboard. We do not provide support for 3rd party software, plugins or libraries that you might have used with our products.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Security</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">Iqonic Design does not process any order payments through the website. All payments are processed securely through RazorPay and Stripe, a third party online payment providers.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Cookie Policy</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server. Our website uses cookies. By using our website and agreeing to this policy, you consent to our use of cookies in accordance with the terms of this policy.<br /><br style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;" />We use session cookies to personalize the website for each user.<br /><br style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;" />We use Google Analytics to analyze the use of our website. Our analytics service provider generates statistical and other information about website use by means of cookies. Deleting cookies will have a negative impact on the usability of the site. If you block cookies, you will not be able to use all the features on our website.<br /><br /></p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Refunds</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">You can ask for refund against the item purchased under certain circumstances listed in our Refund Policy. In the event that you meet the applicable mark for receiving refund, Iqonic Design will issue you a refund and ask you to specify how the product turned down your item performance expectations.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Email</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">By signing up on our website https://iqonic.design you agree to receive emails from us &ndash; Transactional as well as promotional (occasional).</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Ownership</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">Ownership of the product is governed by the usage license.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Changes about terms</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">We may change/update our terms of use without any prior notice. If we change our terms and condition, we will post those changes on this page. Users can check latest version in here.</p>
<p>&nbsp;</p>',
            ),
            7 =>
            array (
                'id' => 8,
                'key' => 'privacy_policy',
                'type' => 'privacy_policy',
            'value' => '<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">This Privacy Policy is brought by Iqonic Design. Iqonic Design is the sole owner of a number of demo websites containing previews of WordPress website themes. This Privacy Policy shall apply to all Iqonic Design sites where this Privacy Policy is featured. This Privacy Policy describes how the Iqonic Design collects, uses, shares and secures personal information that you provide.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">Iqonic Design does not share personal information of any kind with anyone. We will not sell or rent your name or personal information to any third party. We do not sell, rent or provide outside access to our mailing list or any data we store. Any data that a user stores via our facilities is wholly owned by that user or business. At any time, a user or business is free to take their data and leave, or to simply delete their data from our facilities.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">Iqonic Design only collects specific personal information that is necessary for you to access and use our services. This personal information includes, but is not limited to, first and last name, email address, Country of residence.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">Iqonic Design may release personal information if Iqonic Design is required to by law, search warrant, subpoena, court order or fraud investigation. We may also use personal information in a manner that does not identify you specifically nor allow you to be contacted but does identify certain criteria about our site&rsquo;s users in general (such as we may inform third parties about the number of registered users, number of unique visitors, and the pages most frequently browsed).</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">&nbsp;</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Use of Information</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">We use the information to enable your use of the site and its features and to assure security of use and prevent any potential abuse. We may use the information that we collect for a variety of purposes including:</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Promotion</span>&nbsp;&mdash; With your consent we send promotional communications, such as providing you with information about products and services, features, surveys, newsletters, offers, promotions, contests and events;</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Safety and security</span>&nbsp;&mdash; We use the information we have to verify accounts and activities, combat harmful conduct, detect and prevent spam and other bad experiences, maintain the integrity of the Platform, and promote safety and security.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Product research and development</span>&nbsp;&mdash; We use the information we have to develop, test and improve our Platform and Services, by conducting surveys and research, and testing and troubleshooting new products and features.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;"><span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; font-weight: bolder;">Communication with you</span>&nbsp;&mdash; We use the information we have to send you various communications, communicate with you about our products, and let you know about our policies and terms. We also use your information to respond to you when you contact us.</p>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">&nbsp;</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;">Amendments</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">We may amend this Privacy Policy from time to time. When we amend this Privacy Policy, we will update this page accordingly and require you to accept the amendments in order to be permitted to continue using our services.</p>
<h5 style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 0px; font-family: Conv_Hero-Regular, sans-serif; font-weight: var(--font-weight-h5); line-height: var(--font-line-height-h5); color: var(--wp--preset--color--title); font-size: var(--font-size-h5); font-stretch: condensed; clear: both; overflow-wrap: break-word; letter-spacing: var(--font-letter-spacing-h5); background-color: #ffffff;"><br style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;" />Contact Us</h5>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; margin: 15px 0px; line-height: 1.66em; font-family: var(--global-font-family); font-size: 20px; color: var(--wp--preset--color--body); background-color: #ffffff;">You can learn more about how privacy works within our site by contacting us. If you have questions about this Policy, you can contact us via email address provided. Additionally, we may also resolve any disputes you have with us in connection with our privacy policies and practices through direct contact. Write to us at&nbsp;<span style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; transition: all 0.5s ease-in-out 0s; text-decoration-line: underline;"><em style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / 0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000;">hello@iqonic.design</em></span></p>
<p>&nbsp;</p>',
            ),
            8 =>
            array (
                'id' => 9,
                'key' => 'refund_cancellation_policy',
                'type' => 'refund_cancellation_policy',
                'value' => '<p dir="ltr">At Handyman, we are committed to providing you with high-quality services that meet your needs and exceed your expectations. However, we understand that things do not always go according to plan, and sometimes cancellations or refunds might be necessary. This policy outlines the circumstances under which you can request a refund or cancel a booking made through the Handyman mobile app.</p>
                            <p dir="ltr"><strong>Cancellations &amp; :</strong></p>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Unavailability of Handyman: You can cancel any booking free of charge until the provider accepts it. To cancel, open the Handyman Customer App, navigate to your booking details, and tap "Cancel Booking." If you cancel before the provider accepts your booking, you will receive a full refund of the service fee for advance booking services.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Unavailability of Handyman: In the rare event that a Handyman is unable to make it to your scheduled appointment due to unforeseen circumstances, the provider can decline your service.</p>
                            </li>
                            </ul>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Reschedule your appointment: We will work with you to find a new appointment time that suits your needs.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Cancel your booking and receive a full refund: No cancellation fee will be applied (If this service is based on advance booking service).</p>
                            </li>
                            </ul>
                            <p><strong>Refunds:</strong></p>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Refunds will be processed into the users wallet if this service is based on Advance booking service.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">The following situations are not eligible for a full refund:&nbsp;</p>
                            </li>
                            </ul>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">You cancel your booking before the provider accepts it.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">You are not satisfied with the quality of the work performed, but the Handyman completed the service as described in the app.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">You experience minor inconveniences or delays during the service.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">You request changes to the scope of the service after the Handyman has arrived, which may result in additional charges.</p>
                            </li>
                            </ul>
                            <p dir="ltr"><strong>Dispute Resolution:</strong></p>
                            <p dir="ltr">If you have any concerns or disagreements regarding your refund or cancellation request, please contact Handyman customer support at <a href="mailto:hello@iqonic.design">hello@iqonic.design</a> or call us at +1234567890. We are committed to resolving all issues fairly and amicably.</p>
                            <p dir="ltr">Important Notes:&nbsp;</p>
                            <ul>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">This Refund and Cancellation Policy applies to all bookings made through the Handyman App or Website.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">Handyman reserves the right to modify this policy at any time without prior notice. The latest version of this policy will always be available on the Handyman website and mobile app.</p>
                            </li>
                            <li dir="ltr" aria-level="1">
                            <p dir="ltr" role="presentation">By using the Handyman mobile app, you agree to be bound by this Refund and Cancellation Policy.</p>
                            </li>
                            </ul>
                            <p dir="ltr">We hope this policy clarifies the process for requesting refunds and cancellations on the Handyman app. If you have any questions, please feel free to contact our customer support team.</p>
                            <p>&nbsp;</p>
                            <p dir="ltr">Sincerely,</p>
                            <p dir="ltr">The Handyman Team</p>',
            ),
            9 =>
            array (
                'id' => 10,
                'key' => 'help_support',
                'type' => 'help_support',
                'value' => '<p>Contact Us for Support</p>
                            <p>Email</p>
                            <p>Email us at : hello@iqonic.design<br /><br />Telephone</p>
                            <p>Call us at : +1234567890<br /><br />Additional Information</p>
                            <p>If you need further assistance or have specific inquiries, feel free to reach out through the provided contact options.</p>',
            ),
            10 =>
            array (
                'id' => 11,
                'key' => 'cookie-setup',
                'type' => 'cookie-setup',
                'value' => '{"title":"Cookie Notice","description":"We use cookies for better browsing, personalized content, and traffic analysis. Click `Accept All` to consent."}',
            ),
            11 =>
            array (
                'id' => 12,
                'key' => 'earning-setting',
                'type' => 'earning-setting',
                'value' => 'commission',
            ),
            12 =>
                        array (
                            'id' => 13,
                            'key' => 'data_deletion_request',
                            'type' => 'data_deletion_request',
                            'value' => '<p dir="ltr">To ensure the safety and privacy of your data, we offer a streamlined process for requesting its removal from our servers. To initiate the deletion process, kindly send an email from your registered email address to our dedicated email inbox at <strong>hello@iqonic.design</strong> Upon based on your request, our team will thoroughly examine the provided details and proceed with necessary actions in adherence to our privacy policies and legal obligations.  </p>
                            <p>&nbsp;</p>
                            <p dir="ltr">Sincerely,</p>
                            <p dir="ltr">The Handyman Team</p>',
            ),

        ));


    }
}
